name: Lint
on:
  push:
  pull_request:
jobs:
  lint:
    name: Luacheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.1.4"
      - name: luacheck
        uses: nebularg/actions-luacheck@v1.1.0
        with:
          files: ClassicLootManager.lua Integration.lua Migration.lua MinimapIcon.lua Utils.lua Alerts/ Global/ Modules/ Locale/
